DXLM-7085 : TIE servers are not connected in DXL
opendxl/opendxl-client-java pull request #24
Opened 2022-04-11 12:19 UTC by sonu-mcafee

2022-04-13 07:30 UTC, rajkamal-trellix approved these changes
Reviewed.

2022-04-14 02:59 UTC, kjain-mcafee requested changes

2022-04-14 02:59 UTC, kjain-mcafee commented on src/main/java/com/opendxl/client/DxlClientConfig.java
> +                    logger.info("Error shutting down getSortedBrokerList executor service thread pool"
Can you change this to "warn" level and message start with "Not able to shutdown" instead of "Error shutting down.."

2022-04-14 05:41 UTC, kjain-mcafee commented
closing this one

2022-04-14 05:41 UTC, closed without merging