Gradle Migrated To : 7.4 and log4j To 2.17.1
opendxl/opendxl-client-java pull request #25
Opened 2022-04-12 09:14 UTC by sonu-mcafee

2022-04-13 07:30 UTC, rajkamal-trellix approved these changes
Reviewed.

2022-04-14 03:08 UTC, kjain-mcafee requested changes

2022-04-14 03:08 UTC, kjain-mcafee commented on build.gradle
> +    //implementation 'org.apache.logging.log4j:log4j-1.2-api:2.17.1' Bridging API Can't Be use as Project has appenders and filters
Please remove commented lines

2022-04-14 03:08 UTC, kjain-mcafee commented on docs/conf.py
> +copyright = u'2022, Trellix'
change Trellix to '2022, Musarubra US LLC'

2022-04-14 03:53 UTC, kjain-mcafee approved these changes

2022-04-14 05:40 UTC, kjain-mcafee approved these changes

2022-04-20 10:02 UTC, merged